[winclient]
ferslong=off

[winclient.dll]
comdll=sqloraw

[win32client.dll]
comdll=sqlora32

[oragtwy]
longbuffer=32767
fetchrow=20
maperror=OFF
;uselob=1
;
remotedbname=NID_DEV,@TNS:INCA_dev.incaworld
remotedbname=NID_ACC,@TNS:INCA_acc.incaworld
remotedbname=NID_EDU,@TNS:INCA_edu.incaworld
remotedbname=NID_PRD,@TNS:INCA_prd.incaworld
remotedbname=NID_RES,@TNS:INCA_res.incaworld
remotedbname=NID_SIT,@TNS:INCA_sit.incaworld
remotedbname=NID_UAT,@TNS:INCA_uat.incaworld
remotedbname=NID_WRES,@TNS:INCA_dev.incaworld

[sqsgtwy]
